version: '3.8'

services:
  nextdash-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Load from .env.local
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - nextdash-dev-network
    command: npm run dev

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - nextdash-dev-network
    command: redis-server --appendonly yes

  # Development database (optional - for local development without Hostinger)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextdash_dev
      - MYSQL_USER=nextdash
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds:/docker-entrypoint-initdb.d/seeds
    restart: unless-stopped
    networks:
      - nextdash-dev-network

volumes:
  uploads:
  redis_dev_data:
  mysql_dev_data:

networks:
  nextdash-dev-network:
    driver: bridge