version: '3.8'

# Hostinger-optimized Docker Compose configuration
# This version is designed for deployment on Hostinger with external database

services:
  nextdash-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # App Configuration
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-NextDash-B}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NODE_ENV=production
      
      # External Database Configuration (Hostinger)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=false
      
      # Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      
      # Worker Configuration (disabled for single container)
      - WORKER_ENABLED=false
      
      # Security
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      
      # Admin Users
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
      - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
      - ADMIN2_EMAIL=${ADMIN2_EMAIL}
      - ADMIN2_PASSWORD=${ADMIN2_PASSWORD}
      - ADMIN2_FIRST_NAME=${ADMIN2_FIRST_NAME}
      - ADMIN2_LAST_NAME=${ADMIN2_LAST_NAME}
    volumes:
      - uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - default
    # Health check for external database connectivity
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
  logs:

networks:
  default:
    driver: bridge